name: Test Project

on:
  push:
    branches: [ "main", "gh-actions" ]
  workflow_dispatch:
jobs:
  unit-test:
    #name: Unit tests and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle      

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew clean testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
    
