name: Test Project

on:
  push:
    branches: [ "main", "gh-actions" ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: 'app/build/reports/lint-results-debug.html'

  unit-test:
    needs: [lint]
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#          cache: gradle
#
#      - name: Grant execute permissions for gradlew
#        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew clean testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
            name: unit-test-report
            path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    name: Instrumentation Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
#          script: ./gradlew connectedDebugAndroidTest
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
            name: instrumentation-test-report
            path: app/build/reports/androidTests/connected/
